version: '3.8'

services:
    mysql:
        container_name: mysql-app
        image: mysql:latest
        restart: unless-stopped
        security_opt:
            - seccomp:unconfined
        ports:
            - ${MYSQL_PORT}:${MYSQL_PORT}
        expose:
            - ${MYSQL_PORT}
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - my-db:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin-app
        image: phpmyadmin/phpmyadmin:4.7
        depends_on:
            - mysql
        ports:
            - "30002:80"
        environment:
            - PMA_HOST=mysql-app
            - PMA_PORT=${MYSQL_PORT}
            - PMA_ARBITRARY=1
        volumes:
            - /sessions
    dev:
        container_name: mailer_api_dev
        image: mailer-api-dev
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: yarn start:dev
        expose:
            - ${MYSQL_PORT}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - mysql
volumes:
    my-db: